---

- name: platform dependent vars
  include_vars: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/vars/'
  tags: always

- name: platform dependent tasks
  include_tasks: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/tasks/platform/'
  tags: install

- name: install kibana
  package:
    name: kibana
    state: present
  tags: install

- name: populate service facts
  service_facts:
  tags: always

- name: configure kibana
  template:
    src: "kibana.yml.j2"
    dest: "{{ config_file_path | default(platform['config_file_path']) }}"
  tags: configure

- name: setup services
  systemd:
    name: kibana
    enabled: "{{ service['enabled'] }}"
    state: "{{ 'restarted' if service['state'] == 'started' else service['state'] }}"
  when: ansible_facts['services']['kibana'] is defined 
  tags: always

