---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt repository
      when: 'ansible_pkg_mgr == "apt"'
      apt:
        update_cache: true
  roles:
    - role: ansible-role-kibana
      vars:
        elk_kibana_configuration:
          server:
            host: "0.0.0.0"
            port: "5601"
          elasticsearch:
            url: "http://localhost:9200"

# post_tasks:
#   - name: Kibana should be running on a default port
#     uri:
#       url: http://127.0.0.1:5601/login
#       status_code: 200
#     register: result
#     until: result.status == 200
#     retries: 60
#     delay: 1
