---

- name: Converge
  hosts: all
  roles:
    - kibana

# post_tasks:
#   - name: Kibana should be running on a default port
#     uri:
#       url: http://127.0.0.1:5601/login
#       status_code: 200
#     register: result
#     until: result.status == 200
#     retries: 60
#     delay: 1
